### ISSUE TITLE
[Feature Request] AFK+'X' Minutes Push Alert

### ISSUE THREAD

**Issue by Magic815** [ninthwalker/BattlegroundNotifier#6] opened 2020-10-15 02:50 UTC
Would it be possible to add a feature to this where it alerts the user when a character has been AFK for 'X' minutes? Where 'X' is an amount of time set by the user in the .ps1 file? (Using the same notification methods already established - Pushbullet, Discord, etc.)

My thinking on how it would work:
1. A second scan box would be established over the chat window (with X,Y bounds that can be established in the ,ps1 file), and would be scanning for the line "You are now AFK: Away from Keyboard."
2. Once that occurs, a timer starts.
3. Once that timer reaches the amount of time set by the user in the .ps1 file (let's say 15-20 minutes), it then sends an alert to the user saying "Warning: Your character is about to be logged out for being AFK."

Thoughts? I figure since it's too late to ping off the "you are about to be disconnected" pop-up, the next best thing is triggering off the AFK message in chat, plus a timer that lasts the typical amount of time between going AFK and getting disconnected.

**Comment by ninthwalker** [comment] 2020-10-27 17:33
Someone else asked for this before, but the issue is to make sure to capture the afk message, and still just scan like every 10 seconds, the player would need to make sure to have their chat on like a separate tab, that did not include trade chat for example, otherwise it would scroll past too fast. Scanning every second for chat msg's would be too much imo.

I could prob add this in, or with like a separate afk module/script maybe. But then would people actually remember to change their chat tab when they went AFK? I don't know.

**Comment by Magic815** [comment] 2020-10-27 17:41
I can say I would certainly use the feature, and would do what was necessary to get it working (using a fast enough scan speed and/or separating other trade chat spam from my chat window).

The feature can always come with a warning/caveat that the AFK notification requires either one of the above things being done by the user to work effectively. For myself, I've made my chat window large enough and would be fine with using a 3 second scan, that would have a good chance to catch the AFK line 99% of the time - even if I don't bother with separating trade chat.

**Comment by ninthwalker** [comment] 2021-11-17 00:00
Closing, I don't play the game much any more and won't be trying to implement this after all. Sorry.

**Closed as completed by ninthwalker** 2021-11-17 00:01 UTC
